# Hydrogram A and B (Resolução ANA 911-2014) for Belo Monte
# http://arquivos.ana.gov.br/resolucoes/2014/ANALegis/LEGISResolucao911-2014.pdf
# The position of each value indicates the month (0: january, 1: february, ..., 11: december)
hydrogram = {
    'A': [1100, 1600, 2500, 4000, 1800, 1200, 1000, 900, 750, 700, 800, 900],
    'B': [1100, 1600, 4000, 8000, 4000, 2000, 1200, 900, 750, 700, 800, 900],
    'A_B': [1100, 1600, 3250, 6000, 2900, 1600, 1100, 900, 750, 700, 800, 900],
    'IBAMA': [3100, 10900, 14200, 13400, 5200, 1800, 1300, 900, 750, 760, 1000, 1200]
}

hydrogram_used = hydrogram['B']

# Dictionary containing the natural and artificial code for each station
stations_code = {
1: {'name': ['Camargos'], 'id_nat': [1], 'id_art': [None]},
2: {'name': ['Itutinga'], 'id_nat': [2], 'id_art': [None]},
4: {'name': ['Funil-MG'], 'id_nat': [211], 'id_art': [None]},
6: {'name': ['Furnas'], 'id_nat': [6], 'id_art': [None]},
7: {'name': ['Mascarenhas de Moraes'], 'id_nat': [7], 'id_art': [None]},
8: {'name': ['Estreito'], 'id_nat': [8], 'id_art': [None]},
9: {'name': ['Jaguara'], 'id_nat': [9], 'id_art': [None]},
10: {'name': ['Igarapava'], 'id_nat': [10], 'id_art': [None]},
11: {'name': ['Volta Grande'], 'id_nat': [11], 'id_art': [None]},
12: {'name': ['Porto Colômbia'], 'id_nat': [12], 'id_art': [None]},
14: {'name': ['Caconde'], 'id_nat': [14], 'id_art': [None]},
15: {'name': ['Euclides da Cunha'], 'id_nat': [15], 'id_art': [None]},
16: {'name': ['Limoeiro'], 'id_nat': [16], 'id_art': [None]},
17: {'name': ['Marimbondo'], 'id_nat': [17], 'id_art': [None]},
18: {'name': ['Água Vermelha'], 'id_nat': [18], 'id_art': [None]},
22: {'name': ['Batalha'], 'id_nat': [22], 'id_art': [None]},
21: {'name': ['Serra do Facão'], 'id_nat': [251], 'id_art': [None]},
24: {'name': ['Emborcação'], 'id_nat': [24], 'id_art': [None]},
25: {'name': ['Nova Ponte'], 'id_nat': [25], 'id_art': [None]},
26: {'name': ['Miranda'], 'id_nat': [206], 'id_art': [None]},
27: {'name': ['Capim Branco 1'], 'id_nat': [207], 'id_art': [None]},
28: {'name': ['Capim Branco 2'], 'id_nat': [28], 'id_art': [None]},
29: {'name': ['Corumbá IV'], 'id_nat': [205], 'id_art': [None]},
30: {'name': ['Corumbá I'], 'id_nat': [209], 'id_art': [None]},
31: {'name': ['Itumbiara'], 'id_nat': [31], 'id_art': [None]},
32: {'name': ['Cachoeira Dourada'], 'id_nat': [32], 'id_art': [None]},
33: {'name': ['São Simão'], 'id_nat': [33], 'id_art': [None]},
34: {'name': ['Ilha Solteira', 'Ilha Solteira Equivalente'], 'id_nat': [34, 244], 'id_art': [None, 44]},
37: {'name': ['Barra Bonita'], 'id_nat': [237], 'id_art': [37]},
38: {'name': ['Bariri'], 'id_nat': [238], 'id_art': [38]},
39: {'name': ['Ibitinga'], 'id_nat': [239], 'id_art': [39]},
40: {'name': ['Promissão'], 'id_nat': [240], 'id_art': [40]},
42: {'name': ['Nova Avanhandava'], 'id_nat': [242], 'id_art': [42]},
43: {'name': ['Três Irmãos'], 'id_nat': [243], 'id_art': [43]},
45: {'name': ['Jupiá'], 'id_nat': [245], 'id_art': [45]},
46: {'name': ['Porto Primavera'], 'id_nat': [246], 'id_art': [46]},
47: {'name': ['Jurumirim'], 'id_nat': [47], 'id_art': [None]},
48: {'name': ['Piraju'], 'id_nat': [48], 'id_art': [None]},
49: {'name': ['Chavantes'], 'id_nat': [49], 'id_art': [None]},
50: {'name': ['Lucas Nogueira Garcez'], 'id_nat': [50], 'id_art': [None]},
51: {'name': ['Canoas 2'], 'id_nat': [51], 'id_art': [None]},
52: {'name': ['Canoas 1'], 'id_nat': [52], 'id_art': [None]},
54: {'name': ['Santa Branca do Tigagi'], 'id_nat': [54], 'id_art': [None]},
61: {'name': ['Capivara'], 'id_nat': [61], 'id_art': [None]},
62: {'name': ['Taquaruçu'], 'id_nat': [62], 'id_art': [None]},
63: {'name': ['Rosana'], 'id_nat': [63], 'id_art': [None]},
66: {'name': ['Itaipu'], 'id_nat': [266], 'id_art': [66]},
71: {'name': ['Santa Clara PR'], 'id_nat': [71], 'id_art': [None]},
72: {'name': ['Fundão'], 'id_nat': [72], 'id_art': [None]},
73: {'name': ['Jordão'], 'id_nat': [73], 'id_art': [70]},
74: {'name': ['Foz do Areia'], 'id_nat': [74], 'id_art': [None]},
76: {'name': ['Segredo'], 'id_nat': [76], 'id_art': [75]},
77: {'name': ['Salto Santiago'], 'id_nat': [77], 'id_art': [None]},
78: {'name': ['Salto Osório'], 'id_nat': [78], 'id_art': [None]},
82: {'name': ['Salto Caxias'], 'id_nat': [222], 'id_art': [None]},
83: {'name': ['Baixo Iguaçu'], 'id_nat': [81], 'id_art': [None]},
86: {'name': ['Barra Grande'], 'id_nat': [215], 'id_art': [None]},
88: {'name': ['São Roque'], 'id_nat': [88], 'id_art': [None]},
89: {'name': ['Garibaldi'], 'id_nat': [89], 'id_art': [None]},
90: {'name': ['Campos Novos'], 'id_nat': [216], 'id_art': [None]},
91: {'name': ['Machadinho'], 'id_nat': [217], 'id_art': [None]},
92: {'name': ['Itá'], 'id_nat': [92], 'id_art': [None]},
93: {'name': ['Passo Fundo'], 'id_nat': [93], 'id_art': [None]},
94: {'name': ['Monjolinho'], 'id_nat': [220], 'id_art': [None]},
95: {'name': ['Quebra Queixo'], 'id_nat': [286], 'id_art': [None]},
97: {'name': ['Castro Alves'], 'id_nat': [98], 'id_art': [None]},
98: {'name': ['Monte Claro'], 'id_nat': [97], 'id_art': [None]},
99: {'name': ['14 de Julho'], 'id_nat': [284], 'id_art': [None]},
101: {'name': ['São José'], 'id_nat': [102], 'id_art': [None]},
102: {'name': ['Passo São João'], 'id_nat': [103], 'id_art': [None]},
103: {'name': ['Foz Chapecó'], 'id_nat': [94], 'id_art': [None]},
105: {'name': ['Ponte Nova / Alto Tietê'], 'id_nat': [160], 'id_art': [None]},
# 107: {'name': ['Edgard de Souza (c/ tributários)', 'Edgard de Souza (s/ tributários)'], 'id_nat': [161, 164], 'id_art': [None, None]},
107: {'name': ['Edgard de Souza (c/ tributários)'], 'id_nat': [161], 'id_art': [None]},
108: {'name': ['Traição'], 'id_nat': [104], 'id_art': [None]},
109: {'name': ['Pedreira'], 'id_nat': [109], 'id_art': [None]},
110: {'name': ['Ernestina'], 'id_nat': [110], 'id_art': [None]},
111: {'name': ['Passo Real'], 'id_nat': [111], 'id_art': [None]},
112: {'name': ['Jacuí'], 'id_nat': [112], 'id_art': [None]},
113: {'name': ['Itaúba'], 'id_nat': [113], 'id_art': [None]},
114: {'name': ['Dona Francisca'], 'id_nat': [114], 'id_art': [None]},
115: {'name': ['Capivari Cachoeira'], 'id_nat': [115], 'id_art': [None]},
117: {'name': ['Guarapiranga'], 'id_nat': [117], 'id_art': [None]},
118: {'name': ['Billings'], 'id_nat': [118], 'id_art': [None]},
119: {'name': ['Pedras', 'Billings + Pedras', 'Henry Borden'], 'id_nat': [116, 119, None], 'id_art': [None, None, 318]},
120: {'name': ['Jaguari'], 'id_nat': [120], 'id_art': [None]},
121: {'name': ['Paraibuna'], 'id_nat': [121], 'id_art': [None]},
122: {'name': ['Santa Branca'], 'id_nat': [122], 'id_art': [None]},
123: {'name': ['Funil'], 'id_nat': [123], 'id_art': [None]},
124: {'name': ['Lajes'], 'id_nat': [202], 'id_art': [132]},
#125: {'name': ['Santa Cecília', 'Santa Cecília Bombeamento'], 'id_nat': [125, None], 'id_art': [None, 298]},
125: {'name': ['Santa Cecília'], 'id_nat': [125], 'id_art': [None]},
126: {'name': ['Picada'], 'id_nat': [197], 'id_art': [None]},
127: {'name': ['Sobragi'], 'id_nat': [198], 'id_art': [None]},
129: {'name': ['Simplício', 'Anta'], 'id_nat': [None, 129], 'id_art': [126, 127]},
#130: {'name': ['Ilha dos Pombos'], 'id_nat': [130], 'id_art': [299]},
130: {'name': ['Ilha dos Pombos'], 'id_nat': [130], 'id_art': [None]},
131: {'name': ['Nilo Peçanha'], 'id_nat': [None], 'id_art': [131]},
132: {'name': ['Fontes'], 'id_nat': [202], 'id_art': [303]},
133: {'name': ['Pereira Passos'], 'id_nat': [202], 'id_art': [306]},
134: {'name': ['Salto Grande'], 'id_nat': [134], 'id_art': [None]},
135: {'name': ['Porto Estrela'], 'id_nat': [263], 'id_art': [None]},
139: {'name': ['Candonga'], 'id_nat': [149], 'id_art': [None]},
141: {'name': ['Baguari'], 'id_nat': [141], 'id_art': [None]},
143: {'name': ['Aimorés'], 'id_nat': [148], 'id_art': [None]},
144: {'name': ['Mascarenhas'], 'id_nat': [144], 'id_art': [None]},
148: {'name': ['Irapé'], 'id_nat': [255], 'id_art': [None]},
153: {'name': ['São Domingos'], 'id_nat': [154], 'id_art': [None]},
154: {'name': ['Itapebi'], 'id_nat': [188], 'id_art': [None]},
155: {'name': ['Retiro Baixo'], 'id_nat': [155], 'id_art': [None]},
156: {'name': ['Três Marias'], 'id_nat': [156], 'id_art': [None]},
162: {'name': ['Queimado'], 'id_nat': [158], 'id_art': [None]},
169: {'name': ['Sobradinho Incremental', 'Sobradinho'], 'id_nat': [168, 169], 'id_art': [None, None]},
172: {'name': ['Itaparica Incremental', 'Itaparica'], 'id_nat': [171, 172], 'id_art': [None, None]},
173: {'name': ['Moxotó'], 'id_nat': [173], 'id_art': [None]},
174: {'name': ['Paulo Afonso'], 'id_nat': [175], 'id_art': [None]},
176: {'name': ['Complexo Paulo Afonso-Moxotó'], 'id_nat': [176], 'id_art': [None]},
178: {'name': ['Xingó'], 'id_nat': [178], 'id_art': [None]},
180: {'name': ['Tocos', 'Tocos Vertimento'], 'id_nat': [201, None], 'id_art': [None, 317]},
181: {'name': ['Santana', 'Santana Vertimento'], 'id_nat': [203, None], 'id_art': [315, 304]},
182: {'name': ['Vigário'], 'id_nat': [None], 'id_art': [316]},
189: {'name': ['Pedra do Cavalo'], 'id_nat': [254], 'id_art': [None]},
190: {'name': ['Boa Esperança'], 'id_nat': [190], 'id_art': [None]},
192: {'name': ['Guilman-Amorin'], 'id_nat': [262], 'id_art': [None]},
193: {'name': ['Antônio Dias +Sá Carvalho'], 'id_nat': [183], 'id_art': [None]},
195: {'name': ['Jauru'], 'id_nat': [295], 'id_art': [None]},
196: {'name': ['Guaporé'], 'id_nat': [296], 'id_art': [None]},
203: {'name': ['Corumbá III'], 'id_nat': [23], 'id_art': [None]},
204: {'name': ['Cachoeira Caldeirão'], 'id_nat': [204], 'id_art': [None]},
215: {'name': ['Salto Pilão'], 'id_nat': [101], 'id_art': [None]},
217: {'name': ['Rosal'], 'id_nat': [196], 'id_art': [None]},
227: {'name': ['Sinop'], 'id_nat': [227], 'id_art': [None]},
228: {'name': ['Colider'], 'id_nat': [228], 'id_art': [None]},
229: {'name': ['Teles Pires'], 'id_nat': [229], 'id_art': [None]},
230: {'name': ['São Manoel'], 'id_nat': [230], 'id_art': [None]},
241: {'name': ['Salto do Rio Verdinho'], 'id_nat': [241], 'id_art': [None]},
249: {'name': ['Ourinhos'], 'id_nat': [249], 'id_art': [None]},
251: {'name': ['Serra da Mesa'], 'id_nat': [270], 'id_art': [None]},
252: {'name': ['Cana Brava'], 'id_nat': [191], 'id_art': [None]},
253: {'name': ['São Salvador'], 'id_nat': [253], 'id_art': [None]},
257: {'name': ['Peixe Angical'], 'id_nat': [257], 'id_art': [None]},
261: {'name': ['Lajeado'], 'id_nat': [273], 'id_art': [None]},
262: {'name': ['Salto'], 'id_nat': [294], 'id_art': [None]},
267: {'name': ['Estreito Tocantins'], 'id_nat': [271], 'id_art': [None]},
272: {'name': ['Curuá-Una'], 'id_nat': [277], 'id_art': [None]},
275: {'name': ['Tucuruí'], 'id_nat': [275], 'id_art': [None]},
276: {'name': ['Rondon 2'], 'id_nat': [145], 'id_art': [None]},
277: {'name': ['Balbina'], 'id_nat': [269], 'id_art': [None]},
278: {'name': ['Manso'], 'id_nat': [278], 'id_art': [None]},
279: {'name': ['Samuel'], 'id_nat': [279], 'id_art': [None]},
280: {'name': ['Coaracy Nunes'], 'id_nat': [280], 'id_art': [None]},
281: {'name': ['Ponte de Pedra'], 'id_nat': [281], 'id_art': [None]},
283: {'name': ['Santa Clara MG'], 'id_nat': [283], 'id_art': [None]},
284: {'name': ['Ferreira Gomes'], 'id_nat': [297], 'id_art': [None]},
285: {'name': ['Jirau'], 'id_nat': [285], 'id_art': [None]},
286: {'name': ['Santo Antônio do Jari'], 'id_nat': [290], 'id_art': [None]},
287: {'name': ['Santo Antônio'], 'id_nat': [287], 'id_art': [None]},
288: {'name': ['Posto', 'Belo Monte Artificial'], 'id_nat': [300, None], 'id_art': [None, 292]},
290: {'name': ['Espora'], 'id_nat': [99], 'id_art': [None]},
304: {'name': ['Itiquira I e II'], 'id_nat': [259], 'id_art': [None]},
305: {'name': ['Itiquira II'], 'id_nat': [252], 'id_art': [None]},
310: {'name': ['Dardanelos'], 'id_nat': [291], 'id_art': [None]},
311: {'name': ['Caçu'], 'id_nat': [247], 'id_art': [None]},
312: {'name': ['Barra dos Coqueiros'], 'id_nat': [248], 'id_art': [None]},
314: {'name': ['Pimental Artificial'], 'id_nat': [None], 'id_art': [302]},
315: {'name': ['Foz do Rio Claro'], 'id_nat': [261], 'id_art': [None]},
319: {'name': ['Mauá'], 'id_nat': [57], 'id_art': [None]},
921: {'name': ['Tocos_Lajes'], 'id_nat': [None], 'id_art': [921]},
}

incremental_stations = {
    34: {
        'name': 'Ilha Solteira',
        'formula_nat_inc': lambda x: x[0] - x[1] - x[2] - x[3] - x[4] - x[5],
        'formula_inc_nat': lambda x: x[0] + x[1] + x[2] + x[3] + x[4] + x[5],
        'dep_stations': [34, 33, 18, 99, 241, 261],
        'traveltime_natural': [0, 30, 18, 46, 28, 28],
        'traveltime_reserv': [0, 14, 6, 18, 9, 10],
        'type': 'Aggregate-Tiete',
    },
    238: {
        'name': 'Bariri',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [238, 237],
        'type': 'Dist. Incremental',
    },
    239: {
        'name': 'Ibitinga',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [239, 238],
        'traveltime_natural': [0, 24],
        'traveltime_reserv': [0, 18],
        'type': 'Aggregate-Tiete',
    },
    240: {
        'name': 'Promissão',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [240, 239],
        'type': 'Dist. Incremental',
    },
    242: {
        'name': 'Nova Avanhandava',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [242, 240],
        'traveltime_natural': [0, 42],
        'traveltime_reserv': [0, 12],
        'type': 'Aggregate-Tiete',
    },
    243: {
        'name': 'Três Irmãos',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [243, 242],
        'traveltime_natural': [0, 42],
        'traveltime_reserv': [0, 7],
        'type': 'Aggregate-Tiete',
    },
    245: {
        'name': 'Jupiá',
        'formula_nat_inc': lambda x: x[0] - x[1] - x[2],
        'formula_inc_nat': lambda x: x[0] + x[1] + x[2],
        'dep_stations': [245, 34, 243],
        'traveltime_natural': [0, 5, 7],
        'traveltime_reserv': [0, 3, 5],
        'type': 'Aggregate-Tiete',
    },
    246: {
        'name': 'Porto Primavera',
        'formula_nat_inc': lambda x: x[0] - x[1] - x[2],
        'formula_inc_nat': lambda x: x[0] + x[1] + x[2],
        'dep_stations': [246, 245, 154],
        'traveltime_natural': [0, 48, 32],
        'traveltime_reserv': [0, 24, 20],
        'type': 'Aggregate-Tiete',
    },
    266: {
        'name': 'Itaipu',
        'formula_nat_inc': lambda x: x[0] - x[1] - x[2],
        'formula_inc_nat': lambda x: x[0] + x[1] + x[2],
        'dep_stations': [266, 63, 246],
        'traveltime_natural': [0, 48, 48],
        'traveltime_reserv': [0, 48, 48],
        'type': 'Aggregate-Tiete',
    },
    191: {
        'name': 'Cana Brava',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [191, 270],
        'type': 'Dist. Incremental',
    },
    253: {
        'name': 'São Salvador',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [253, 191],
        'type': 'Dist. Incremental',
    },
    257: {
        'name': 'Peixe Angical',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [257, 253],
        'type': 'Dist. Incremental',
    },
    273: {
        'name': 'Lajeado',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [273, 257],
        'type': 'Dist. Incremental',
    },
}

# Dictionary containing the formulae for the special stations
special_stations = {
    118: {
        'name': 'Billings',
        'type': 'Aggregate-Tiete',
        'formula': lambda x: 0.8 * x[0],
        'dep_stations': [119],
    },
    109: {
        'name': 'Pedreira',
        'type': 'Aggregate-Tiete',
        'formula': lambda x: x[0],
        'dep_stations': [118],
    },
    104: {
        'name': 'Traição',
        'type': 'Aggregate-Tiete',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [117, 118],
    },
    # A vazão incremental de Baixo Iguaçu (81) é obtida da vazão incremental de Salto Caxias (222)
    81: {
        'name': 'Baixo Iguaçu',
        'type': 'Baixo Iguaçu',
        'formula': lambda x: 0.8 * x[0],
        'dep_stations': [222],
    },
    # 116: {
    #     'name': 'Pedras',
    #     'type': 'Aggregate-Tiete',
    #     'formula': lambda x: x[0] - x[1],
    #     'dep_stations': [119, 118],
    # },
    # region Remover depois
    # 246: {
    #     'name': 'P. Primavera',
    #     'type': 'Aggregate-Tiete',
    #     'formula': lambda x: x[0] * 0.603,
    #     'dep_stations': [245],
    # },
    # endregion
    # 154: {
    #     'name': 'São Domingos',
    #     'type': 'Dist. Incremental',
    #     'formula': lambda x: x[0] * 0.179,
    #     'dep_stations': [246],
    # },
    238: {
        'name': 'Bariri Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.658,
        'dep_stations': [239],
    },
    240: {
        'name': 'Promissão Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.717,
        'dep_stations': [242],
    },
    191: {
        'name': 'Cana Brava Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.504,
        'dep_stations': [253],
    },
    257: {
        'name': 'Peixe Angical Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.488,
        'dep_stations': [273],
    },
    169: {
        'name': 'Sobradinho',
        'type': 'São Francisco',
        'formula': lambda x: x[0] + x[1] + x[2],
        'delay_time': [0, -2, -2],
        'dep_stations': [168, 156, 158],
    },
    172: {
        'name': 'Itaparica',
        'type': 'Aggregate-SF',
        'formula': lambda x: x[0],
        'dep_stations': [169],
    },
    173: {
        'name': 'Moxotó',
        'type': 'Aggregate-SF',
        'formula': lambda x: x[0],
        'delay_time': [0],
        'dep_stations': [169],
    },
    175: {
        'name': 'P. Afonso 4',
        'type': 'Aggregate-SF',
        'formula': lambda x: x[0],
        'delay_time': [0],
        'dep_stations': [169],
    },
    176: {
        'name': 'Comp. Moxotó',
        'type': 'Aggregate-SF',
        'formula': lambda x: x[0],
        'delay_time': [0],
        'dep_stations': [169],
    },
    178: {
        'name': 'Comp. Moxotó',
        'type': 'Aggregate-SF',
        'formula': lambda x: x[0],
        'delay_time': [0],
        'dep_stations': [169],
    },
    171: {
        'name': 'Itaparica Inc.',
        'type': 'Zeros',
    },
    921: {
        'name': 'Tocos_Lajes',
        'type': 'São Francisco',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [201, 202],
    },
}

calculated_stations_acomph = {
    2: {
        'name': 'Itutinga',
        'type': 'calculated',
        'formula': lambda x: x[0],
        'dep_stations': [1],
    },
    104: {
        'name': 'Traição',
        'type': 'calculated',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [117, 118],
    },
    109: {
        'name': 'Pedreira',
        'type': 'calculated',
        'formula': lambda x: x[0],
        'dep_stations': [118],
    },
    119: {
        'name': 'Bill. + Pedras',
        'type': 'regressed_reverse',
        'formula': lambda x, a0, a1: a0 + a1*x[0],
        'dep_stations': [118],
    },
    116: {
        'name': 'Pedras',
        'type': 'calculated',
        'formula': lambda x: x[0] - x[1],
        'dep_stations': [119, 118],
    },
    298: {
        'name': 'Santa Cecília Bombeamento',
        'type': 'calculated',
        'formula': lambda x: x[0].apply(lambda y: (((y * (119 / 190), 119)[190 < y <= 209], y - 90)[209 < y <= 250], 160)[y > 250]),
        'dep_stations': [125],
    },
    317: {
        'name': 'Tocos Vertimento',
        'type': 'calculated',
        'formula': lambda x: x[0].apply(lambda y: max(0, y - 25)),
        'dep_stations': [201],
    },
    203: {
        'name': 'Santana',
        'type': 'regressed',
        'formula': lambda x, a0, a1: a0 + a1*x[0],
        'dep_stations': [201],
    },
    315: {
        'name': 'Santana',
        'type': 'calculated',
        'formula': lambda x: x[0] - x[1] + x[2] + x[3],
        'dep_stations': [203, 201, 317, 298],
    },
    316: {
        'name': 'Vigário',
        'type': 'calculated',
        'formula': lambda x: x[0].apply(lambda y: min(y, 190)),
        'dep_stations': [315],
    },
    304: {
        'name': 'Santana Vertimento',
        'type': 'calculated',
        'formula': lambda x: x[0] - x[1],
        'dep_stations': [315, 316],
    },
    127: {
        'name': 'Anta',
         'type': 'calculated',
         'formula': lambda x: x[0] - x[1] - x[2] + x[3],
         'dep_stations': [129, 298, 203, 304],
    },
    126: {
         'name': 'Simplício',
         'type': 'calculated',
         'formula': lambda x: x[0].apply(lambda y: (max(0, y - 90), 340)[y >= 430]),
         'dep_stations': [127],
    },
    131: {
        'name': 'Nilo Peçanha',
        'type': 'calculated',
        'formula': lambda x: x[0].apply(lambda y: min(y, 144)),
        'dep_stations': [316],
    },
    160: {
        'name': 'Ponte Nova',
        'type': 'calculated',
        'formula': lambda x: x[0]*(320/(4844-681-700)),
        'dep_stations': [161],
    },
    164: {
        'name': 'E. Souza',
        'type': 'calculated',
        'formula': lambda x: x[0] - x[1] - x[2],
        'dep_stations': [161, 117, 118],
    },
    # 168: {'name': 'Sobrad. Incr.',
    #     'formula': lambda x: x,
    #     'dep_stations': [ ],
    #},
    174: {
         'name': 'P.A.123',
         'type': 'calculated',
         'formula': lambda x: x[0],
         'dep_stations': [173],
    },
    175: {
          'name': 'P.A.4',
          'type': 'calculated',
          'formula': lambda x: x[0],
          'dep_stations': [173],
    },
    292: {
          'name': 'Belo Monte Principal',
          'type': 'belo_monte',
          'formula': lambda x, m: x[0].apply(lambda y: ((y - hydrogram_used[m], 13900)
                                                      [y > hydrogram_used[m] + 13900], 0)
                                                        [y < hydrogram_used[m]]),
          'dep_stations': [288],
    },
    132: {
        'name': 'Lajes',
        'type': 'calculated',
        'formula': lambda x: x[0] + x[1].apply(lambda y: min(y, 25)),
        'dep_stations': [202, 201],
    },
    303: {
        'name': 'Fontes',
        'type': 'calculated',
        'formula': lambda x: x[0].apply(lambda y: (17, y)[y < 17]) + (x[1] - x[2]).apply(lambda z: min(z, 34)),
        'dep_stations': [132, 316, 131],
    },
    306: {
        'name': 'Pereira Passos',
        'type': 'calculated',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [303, 131],
    },
    318: {
        'name': 'Henry Borden',
        'type': 'calculated',
        'formula': lambda x: x[0] + x[1] + x[2] + 0.1 * (x[3] - x[1] - x[2]),
        'dep_stations': [116, 117, 118, 161],
    },
    921: {
        'name': 'Tocos_Lajes',
        'type': 'calculated',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [201, 202],
    }
}


mlt_submarkets = {'Sudeste': [65805, 70900, 69326, 54954, 40060, 32662, 25728, 20616, 19716, 23606, 31431, 48039],
                  'Sul': [7474, 8215, 7010, 6483, 8494, 10387, 10887, 9929, 11549, 13135, 9270, 7390],
                  'Nordeste': [13512, 14256, 14160, 11574, 6988, 4611, 3799, 3314, 2959, 3224, 5303, 9837],
                  'Norte': [15597, 22630, 26690, 27001, 20391, 10664, 5246, 3189, 2274, 2390, 4029, 8271]
                  }
mlt_postos={
    1: {
        'name': ['Camargos'],
        'id_nat': [1],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['SE'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.2076],
        'mlt': {
            'Jan': [242],
            'Fev': [220],
            'Mar': [196],
            'Abr': [133],
            'Mai': [100],
            'Jun': [85],
            'Jul': [71],
            'Ago': [61],
            'Set': [64],
            'Out': [76],
            'Nov': [108],
            'Dez': [176]
        }
    },
    2: {
        'name': ['Itutinga'],
        'id_nat': [2],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.2437],
        'mlt': {
            'Jan': [242],
            'Fev': [220],
            'Mar': [196],
            'Abr': [133],
            'Mai': [100],
            'Jun': [85],
            'Jul': [71],
            'Ago': [61],
            'Set': [64],
            'Out': [76],
            'Nov': [108],
            'Dez': [176]
        }
    },
    6: {
        'name': ['Furnas'],
        'id_nat': [6],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.8130],
        'mlt': {
            'Jan': [1702],
            'Fev': [1588],
            'Mar': [1421],
            'Abr': [966],
            'Mai': [707],
            'Jun': [593],
            'Jul': [484],
            'Ago': [398],
            'Set': [413],
            'Out': [491],
            'Nov': [704],
            'Dez': [1204]
        }
    },
    7: {
        'name': ['M.Moraes'],
        'id_nat': [7],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.3471],
        'mlt': {
            'Jan': [1901],
            'Fev': [1788],
            'Mar': [1604],
            'Abr': [1093],
            'Mai': [797],
            'Jun': [664],
            'Jul': [541],
            'Ago': [445],
            'Set': [459],
            'Out': [545],
            'Nov': [777],
            'Dez': [1328]
        }
    },
    8: {
        'name': ['Estreito'],
        'id_nat': [8],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.5437],
        'mlt': {
            'Jan': [1943],
            'Fev': [1837],
            'Mar': [1649],
            'Abr': [1128],
            'Mai': [819],
            'Jun': [682],
            'Jul': [555],
            'Ago': [456],
            'Set': [468],
            'Out': [555],
            'Nov': [792],
            'Dez': [1328]
        }
    },
    9: {
        'name': ['Jaguara'],
        'id_nat': [9],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.3944],
        'mlt': {
            'Jan': [1959],
            'Fev': [1857],
            'Mar': [1668],
            'Abr': [1144],
            'Mai': [829],
            'Jun': [689],
            'Jul': [561],
            'Ago': [461],
            'Set': [472],
            'Out': [560],
            'Nov': [797],
            'Dez': [1357]
        }

    },
    10: {
        'name': ['Igarapava'],
        'id_nat': [10],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.1523],
        'mlt': {
            'Jan': [2008],
            'Fev': [1917],
            'Mar': [1723],
            'Abr': [1187],
            'Mai': [856],
            'Jun': [711],
            'Jul': [578],
            'Ago': [474],
            'Set': [483],
            'Out': [572],
            'Nov': [813],
            'Dez': [1381]
        }

    },
    11: {
        'name': ['Volta Grande'],
        'id_nat': [11],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.2482],
        'mlt': {
            'Jan': [2120],
            'Fev': [2042],
            'Mar': [1838],
            'Abr': [1276],
            'Mai': [915],
            'Jun': [757],
            'Jul': [614],
            'Ago': [503],
            'Set': [509],
            'Out': [602],
            'Nov': [853],
            'Dez': [1445]
        }
    },
    12: {
        'name': ['PortoColombia'],
        'id_nat': [12],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.2012],
        'mlt': {
            'Jan': [2393],
            'Fev': [2332],
            'Mar': [2108],
            'Abr': [1476],
            'Mai': [1053],
            'Jun': [865],
            'Jul': [699],
            'Ago': [571],
            'Set': [572],
            'Out': [678],
            'Nov': [957],
            'Dez': [1615]
        }

    },
    14: {
        'name': ['Caconde'],
        'id_nat': [14],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.8259],
        'mlt': {
            'Jan': [94],
            'Fev': [96],
            'Mar': [85],
            'Abr': [58],
            'Mai': [43],
            'Jun': [35],
            'Jul': [29],
            'Ago': [24],
            'Set': [25],
            'Out': [30],
            'Nov': [39],
            'Dez': [68]
        }

    },
    15: {
        'name': ['EuclidesdaCunha'],
        'id_nat': [15],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.7502],
        'mlt': {
            'Jan': [154],
            'Fev': [158],
            'Mar': [139],
            'Abr': [94],
            'Mai': [69],
            'Jun': [58],
            'Jul': [47],
            'Ago': [40],
            'Set': [41],
            'Out': [49],
            'Nov': [63],
            'Dez': [111]
        }
    },
    16: {
        'name': ['A.S.Oliveria'],
        'id_nat': [16],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.2209],
        'mlt': {
            'Jan': [156],
            'Fev': [160],
            'Mar': [141],
            'Abr': [95],
            'Mai': [70],
            'Jun': [59],
            'Jul': [48],
            'Ago': [41],
            'Set': [42],
            'Out': [50],
            'Nov': [64],
            'Dez': [112]
        }
    },
    17: {
        'name': ['Maribondo'],
        'id_nat': [17],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.5183],
        'mlt': {
            'Jan': [3196],
            'Fev': [3262],
            'Mar': [2954],
            'Abr': [2117],
            'Mai': [1520],
            'Jun': [1277],
            'Jul': [1037],
            'Ago': [861],
            'Set': [848],
            'Out': [976],
            'Nov': [1324],
            'Dez': [2174]
        }
    },
    18: {
        'name': ['A.Vermelha'],
        'id_nat': [18],
        'id_art': [None],
        'Bacia': ['Grande'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [1],
        'COD REF': [10],
        'Prod': [0.4625],
        'mlt': {
            'Jan': [3571],
            'Fev': [3698],
            'Mar': [3368],
            'Abr': [2433],
            'Mai': [1740],
            'Jun': [1467],
            'Jul': [1195],
            'Ago': [998],
            'Set': [976],
            'Out': [1124],
            'Nov': [1493],
            'Dez': [2410]
        }
    },
    20: {
        'name': ['BatalhaArtificial'],
        'id_nat': [22],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.3551],
        'mlt': {
            'Jan': [315],
            'Fev': [318],
            'Mar': [291],
            'Abr': [208],
            'Mai': [93],
            'Jun': [71],
            'Jul': [55],
            'Ago': [44],
            'Set': [37],
            'Out': [44],
            'Nov': [76],
            'Dez': [141]
        }
    },
    22: {
        'name': ['Batalha'],
        'id_nat': [22],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.3551],
        'mlt': {
            'Jan': [184],
            'Fev': [189],
            'Mar': [193],
            'Abr': [146],
            'Mai': [93],
            'Jun': [71],
            'Jul': [55],
            'Ago': [44],
            'Set': [37],
            'Out': [44],
            'Nov': [76],
            'Dez': [141]
        }
    },
    23: {
        'name': ['CorumbaIII'],
        'id_nat': [23],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.3471],
        'mlt': {
            'Jan': [260],
            'Fev': [288],
            'Mar': [291],
            'Abr': [230],
            'Mai': [144],
            'Jun': [105],
            'Jul': [82],
            'Ago': [65],
            'Set': [56],
            'Out': [73],
            'Nov': [121],
            'Dez': [195]
        }
    },
    24: {
        'name': ['Emborcacao'],
        'id_nat': [24],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [1.1582],
        'mlt': {
            'Jan': [860],
            'Fev': [863],
            'Mar': [833],
            'Abr': [604],
            'Mai': [385],
            'Jun': [295],
            'Jul': [235],
            'Ago': [189],
            'Set': [166],
            'Out': [197],
            'Nov': [344],
            'Dez': [639]
        }
    },
    25: {
        'name': ['NovaPonte'],
        'id_nat': [25],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.9669],
        'mlt': {
            'Jan': [508],
            'Fev': [514],
            'Mar': [486],
            'Abr': [362],
            'Mai': [249],
            'Jun': [195],
            'Jul': [160],
            'Ago': [130],
            'Set': [119],
            'Out': [146],
            'Nov': [220],
            'Dez': [366]
        }
    },
    28: {
        'name': ['C.Branco2'],
        'id_nat': [28],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.4169],
        'mlt': {
            'Jan': [614],
            'Fev': [625],
            'Mar': [593],
            'Abr': [449],
            'Mai': [308],
            'Jun': [242],
            'Jul': [200],
            'Ago': [166],
            'Set': [151],
            'Out': [182],
            'Nov': [270],
            'Dez': [442]
        }
    },
    31: {
        'name': ['Itumbiara'],
        'id_nat': [31],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.7027],
        'mlt': {
            'Jan': [2621],
            'Fev': [2725],
            'Mar': [2678],
            'Abr': [1999],
            'Mai': [1292],
            'Jun': [995],
            'Jul': [790],
            'Ago': [632],
            'Set': [559],
            'Out': [678],
            'Nov': [1113],
            'Dez': [1921]
        }
    },
    32: {
        'name': ['C.Dourada'],
        'id_nat': [32],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.2702],
        'mlt': {
            'Jan': [2743],
            'Fev': [2861],
            'Mar': [2812],
            'Abr': [2105],
            'Mai': [1363],
            'Jun': [1051],
            'Jul': [837],
            'Ago': [671],
            'Set': [594],
            'Out': [714],
            'Nov': [1167],
            'Dez': [2010]
        }
    },
    33: {
        'name': ['São Simão'],
        'id_nat': [33],
        'id_art': [None],
        'Bacia': ['Paranaíba'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [2],
        'COD REF': [10],
        'Prod': [0.6355],
        'mlt': {
            'Jan': [3951],
            'Fev': [4142],
            'Mar': [4144],
            'Abr': [3161],
            'Mai': [2068],
            'Jun': [1612],
            'Jul': [1295],
            'Ago': [1055],
            'Set': [948],
            'Out': [1121],
            'Nov': [1740],
            'Dez': [2921]
        }
    },
    34: {
        'name': ['Ilha Solteira'],
        'id_nat': [34],
        'id_art': [None],
        'Bacia': ['Alto Parana'],
        'REE': ['Parana'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [5],
        'COD REF': [10],
        'Prod': [0.3869],
        'mlt': {
            'Jan': [8679],
            'Fev': [9116],
            'Mar': [8813],
            'Abr': [6618],
            'Mai': [4550],
            'Jun': [3720],
            'Jul': [3037],
            'Ago': [2545],
            'Set': [2412],
            'Out': [2783],
            'Nov': [3861],
            'Dez': [6173]
        }
    },
37: {
        'name': ['Barra Bonita Artficial'],
        'id_nat': [37],
        'id_art': [None],
        'Bacia': ['Tietê'],
        'REE': ['Sudeste'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [3],
        'COD REF': [1],
        'Prod': [0.1776],
        'mlt': {
            'Jan': [683],
            'Fev': [716],
            'Mar': [610],
            'Abr': [396],
            'Mai': [316],
            'Jun': [319],
            'Jul': [249],
            'Ago': [210],
            'Set': [225],
            'Out': [275],
            'Nov': [304],
            'Dez': [458]
        }
    },
    38: {
        'name': ['Bariri Artificial'],
        'id_nat': [38],
        'id_art': [None],
        'Bacia': ['Tietê'],
        'REE': ['Sudeste'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [3],
        'COD REF': [1],
        'Prod': [0.1848],
        'mlt': {
            'Jan': [765],
            'Fev': [805],
            'Mar': [689],
            'Abr': [452],
            'Mai': [361],
            'Jun': [364],
            'Jul': [284],
            'Ago': [241],
            'Set': [256],
            'Out': [309],
            'Nov': [343],
            'Dez': [512]
        }
    },
    39: {
        'name': ['Ibitinga Artificial'],
        'id_nat': [39],
        'id_art': [None],
        'Bacia': ['Tietê'],
        'REE': ['Sudeste'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [3],
        'COD REF': [1],
        'Prod': [0.1737],
        'mlt': {
            'Jan': [912],
            'Fev': [956],
            'Mar': [825],
            'Abr': [559],
            'Mai': [450],
            'Jun': [449],
            'Jul': [358],
            'Ago': [306],
            'Set': [322],
            'Out': [381],
            'Nov': [420],
            'Dez': [620]
        }
    },
    40: {
        'name': ['Promissão Artificial'],
        'id_nat': [40],
        'id_art': [None],
        'Bacia': ['Tietê'],
        'REE': ['Sudeste'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [3],
        'COD REF': [1],
        'Prod': [0.2130],
        'mlt': {
            'Jan': [1101],
            'Fev': [1155],
            'Mar': [1008],
            'Abr': [679],
            'Mai': [547],
            'Jun': [543],
            'Jul': [438],
            'Ago': [380],
            'Set': [398],
            'Out': [463],
            'Nov': [507],
            'Dez': [747]
        }
    },
    42: {
    'name': ['Nova Navanhadava Artificial'],
    'id_nat': [42],
    'id_art': [None],
    'Bacia': ['Tietê'],
    'REE': ['Sudeste'],
    'SUB': ['Sudeste'],
    'COD SUB': [1],
    'COD BACIA': [3],
    'COD REF': [1],
    'Prod': [0.2784],
    'mlt': {
        'Jan': [1184],
        'Fev': [1246],
        'Mar': [1083],
        'Abr': [728],
        'Mai': [583],
        'Jun': [580],
        'Jul': [466],
        'Ago': [403],
        'Set': [422],
        'Out': [493],
        'Nov': [541],
        'Dez': [799]
        }
    },
    43: {
    'name': ['Tres Irmaos Art'],
    'id_nat': [243],
    'id_art': [43],
    'Bacia': ['Tietê'],
    'REE': ['Sudeste'],
    'SUB': ['Sudeste'],
    'COD SUB': [1],
    'COD BACIA': [3],
    'COD REF': [1],
    'Prod': [0.4025],
    'mlt': {
        'Jan': [1240],
        'Fev': [1329],
        'Mar': [1169],
        'Abr': [797],
        'Mai': [625],
        'Jun': [624],
        'Jul': [503],
        'Ago': [436],
        'Set': [450],
        'Out': [524],
        'Nov': [572],
        'Dez': [836]
       }
    },
    47: {
        'name': ['Jurumirim'],
        'id_nat': [47],
        'id_art': [None],
        'Bacia': ['Paranapanema'],
        'REE': ['Paranapanema (SE)'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [4],
        'COD REF': [12],
        'Prod': [0.2907],
        'mlt': {
            'Jan': [328],
            'Fev': [360],
            'Mar': [306],
            'Abr': [217],
            'Mai': [192],
            'Jun': [203],
            'Jul': [175],
            'Ago': [146],
            'Set': [158],
            'Out': [188],
            'Nov': [183],
            'Dez': [230]
        }
    },
    48: {
        'name': ['Piraju'],
        'id_nat': [48],
        'id_art': [None],
        'Bacia': ['Paranapanema'],
        'REE': ['Paranapanema (SE)'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [4],
        'COD REF': [12],
        'Prod': [0.2306],
        'mlt': {
            'Jan': [335],
            'Fev': [368],
            'Mar': [314],
            'Abr': [222],
            'Mai': [196],
            'Jun': [209],
            'Jul': [180],
            'Ago': [150],
            'Set': [162],
            'Out': [193],
            'Nov': [187],
            'Dez': [235]
        }
    },
    49: {
        'name': ['Chavantes'],
        'id_nat': [49],
        'id_art': [None],
        'Bacia': ['Paranapanema'],
        'REE': ['Paranapanema (SE)'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [4],
        'COD REF': [12],
        'Prod': [0.6177],
        'mlt': {
            'Jan': [510],
            'Fev': [535],
            'Mar': [446],
            'Abr': [321],
            'Mai': [300],
            'Jun': [319],
            'Jul': [276],
            'Ago': [228],
            'Set': [254],
            'Out': [303],
            'Nov': [286],
            'Dez': [349]
        }
    },
    50: {
        'name': ['L.N.Garcez'],
        'id_nat': [50],
        'id_art': [None],
        'Bacia': ['Paranapanema'],
        'REE': ['Paranapanema (SE)'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [4],
        'COD REF': [12],
        'Prod': [0.1483],
        'mlt': {
            'Jan': [663],
            'Fev': [703],
            'Mar': [599],
            'Abr': [442],
            'Mai': [409],
            'Jun': [432],
            'Jul': [369],
            'Ago': [310],
            'Set': [338],
            'Out': [396],
            'Nov': [381],
            'Dez': [463]
        }
    },
    53: {
    'name': ['Canoas Ii'],
    'id_nat': [53],
    'id_art': [None],
    'Bacia': ['Paranapanema (SE)'],
    'REE': ['Paranapanema'],
    'SUB': ['Sudeste'],
    'COD SUB': [1],
    'COD BACIA': [4],
    'COD REF': [12],
    'Prod': [0.1288],
    'mlt': {
        'Jan': [673],
        'Fev': [716],
        'Mar': [611],
        'Abr': [452],
        'Mai': [417],
        'Jun': [441],
        'Jul': [376],
        'Ago': [316],
        'Set': [344],
        'Out': [403],
        'Nov': [388],
        'Dez': [472]
        }
    },
    54:  {
    'name': ['Canoas I'],
    'id_nat': [54],
    'id_art': [None],
    'Bacia': ['Paranapanema (SE)'],
    'REE': ['Paranapanema'],
    'SUB': ['Sudeste'],
    'COD SUB': [1],
    'COD BACIA': [4],
    'COD REF': [12],
    'Prod': [0.1489],
    'mlt': {
        'Jan': [697],
        'Fev': [743],
        'Mar': [636],
        'Abr': [471],
        'Mai': [434],
        'Jun': [459],
        'Jul': [392],
        'Ago': [330],
        'Set': [357],
        'Out': [418],
        'Nov': [404],
        'Dez': [490]
        }
    },
    55: {
        'name': ['Tibagi Mont'],
        'id_nat': [55],
        'id_art': [None],
        'Bacia': ['Paranapanema (SE)'],
        'REE': ['Paranapanema'],
        'SUB': ['Sudeste'],
        'COD SUB': [1],
        'COD BACIA': [4],
        'COD REF': [12],
        'Prod': [None],
        'mlt': {
            'Jan': [188],
            'Fev': [188],
            'Mar': [159],
            'Abr': [118],
            'Mai': [145],
            'Jun': [184],
            'Jul': [186],
            'Ago': [150],
            'Set': [167],
            'Out': [218],
            'Nov': [178],
            'Dez': [160]
        }
    },
    57: {
    'name': ['Mauá'],
    'id_nat': [57],
    'id_art': [None],
    'Bacia': ['Paranapanema (S)'],
    'REE': ['Iguaçu'],
    'SUB': ['Sul'],
    'COD SUB': [2],
    'COD BACIA': [27],
    'COD REF': [11],
    'Prod': [1.0494],
    'mlt': {
        'Jan': [309],
        'Fev': [310],
        'Mar': [259],
        'Abr': [192],
        'Mai': [234],
        'Jun': [292],
        'Jul': [285],
        'Ago': [227],
        'Set': [256],
        'Out': [336],
        'Nov': [280],
        'Dez': [255]
        }
    },



}